language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: matt@mattblair.co
  api_key:
    secure: FG0AuIAMlfGF4R/X5CE5mFMYfHnVQ2/MC9O/5r2spZpkLf/dTcKT6zZNvzAuEAkSBWA8z1DJ47C8NkY9vIU9PDhhRtQ+Go0Ze78jpBDQ+CfN9ynaNGbA9bWOkFABvqE+CV4JPBTccOC4aCJYKHWC2eEPIjd/Ahpu4lhyub54YPU=
  on:
    tags: true
    repo: duereg/automated-readability-index
